ACTIVE_PROFILE: prod

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"
POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmeinmomo
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

SERVER_PORT: 8080
UI_APP_URL: http://localhost:3000
